### ISSUE TITLE
Request for the scripts of generating graph.json file

### ISSUE THREAD

**Issue by xuelianl** [AndMastro/protein-ligand-GNN#3]
Hello,
    Thank you so much for this public available repo.
    I want to train or test these models on my structures. However, there is no script for generating the input files (i.e., the protein, ligand, and interaction_graph.json) for training or testing. Could you kindly provide the scripts to generate these files?
    Thanks!
Li

**Comment by AndMastro** [comment]
Thank you for reaching out! The input files provided in the [link](http://bioinfo-pharma.u-strasbg.fr/labwebsite/downloads/pdbbind.tgz) in the readme were downloaded from the mentioned link and not generated by us. The processing done for the generation of such files can be found in the paper by the authors of the data: https://pubs.acs.org/doi/abs/10.1021/acs.jmedchem.2c00487. 

Once you have your own data in the same format, you can use them with our code 😁

**Comment by xuelianl** [comment]
> Once you have your own data in the same format, you can use them with our code

Indeed, I have encoded my data in the same format, and it runs successfully.
However, I have noticed some variations in details such as the number of edges and nodes, and I am uncertain about the potential impact on performance.
Nevertheless, I sincerely appreciate your response!
