### ISSUE TITLE
json file not found

### ISSUE THREAD

**Issue by a1e-the** [AndMastro/protein-ligand-GNN#4]
Hi,

Congratulations on your fantastic work!  I successfully run the command "python trainer_script.py" and "python explainer_script.py" with all default settings, but failed to run the command "python top_k_computation.py". It shows that there is something missing:

File "top_k_computation.py", line 51, in generate_pli_dataset_dict_reduced
    with open(data_path + interaction_name + "/" + interaction_name + "_interaction_graph.json", 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data//dataset/.ipynb_checkpoints/.ipynb_checkpoints_interaction_graph.json'

a json file in the dataset folder, i double checked the downloaded pdbbind (1).tgz , and there is no such file.  i wonder how i can get that particular file

**Comment by AndMastro** [comment]
Hello, thanks for reaching out! 😎

It looks like in the downloaded pdbbind dataset, into the ```dataset``` folder, there is a ```.ipynb_checkpoints``` folder you can safely delete. The code searches for all directories in that folder, and it finds the directory ```.ipynb_checkpoints```. Ensure that the ```dataset``` folder contains only folders related to protein-ligand complexes, and you should be fine👌

**Comment by a1e-the** [comment]
I appreciate your reply, it really solved my problem. I successfully generated the svg files.
Wish you all the best!😎
